# Generated by Django 5.0 on 2024-01-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_cart_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('LISTED', 'Listed'), ('SOLD', 'Sold')], default='LISTED', max_length=10),
        ),
    ]
